global:
  message: welcome to global microservices environment!!
logging:
  level:
    root: INFO # Corrected spacing for 'INFO'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6005/eureka/ # Ensure no space between colon and http
management:
  endpoints: # This is the main 'endpoints' block
    web:
      exposure:
        include: health,info,refresh # Use comma-separated list without spaces after comma is fine, but space is better for readability
  endpoint: # Use 'endpoint' (singular) to configure individual endpoints
    health:
      show-details: always
