global:
  message: welcome to order prod environment!!
server:
  port: 6003
message: hello from prod
spring:
   datasource:
    url: jdbc:mysql://localhost:3306/order_prod?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
 
